<?php

return [
    // SECTION 1: Children
    [
        'id' => 1,
        'type' => 'text',
        'category' => 'children',
        'section_id' => 'children',
        'section_title' => 'Children',
        'section_number' => 1,
        'total_sections' => 3,
        'label' => 'Child Main Challenges',
        'order' => 1,
        'question' => 'What are the main challenges your child is facing right now?',
        'participant_behavior' => 'Needs suggestions/context',
        'ai_guidance' => 'This could be explored via context (e.g. at home, at school/college, in the community) or themes (e.g. education, mental/physical health, trauma related behaviours, identity and belonging).',
        'red_flag_criteria' => 'Flag if someone mentions safeguarding concerns, risk of harming themselves or others. Trigger immediate referral to safeguarding@theraftleicester.co.uk.',
    ],
    [
        'id' => 2,
        'type' => 'text',
        'category' => 'children',
        'section_id' => 'children',
        'section_title' => 'Children',
        'section_number' => 1,
        'total_sections' => 3,
        'label' => 'Child Support Worked and Failed',
        'order' => 2,
        'question' => 'What support has helped your child so far, and what has not worked?',
        'participant_behavior' => 'Struggling for suggestions',
        'ai_guidance' => 'Supportive ideas: day care / respite, therapy (e.g. play, music, lego, DDP), school supports (e.g. EHCPs, meeting SEN needs, tutors), sensory interventions, emotional literacy. Not worked: wrong therapy, problems accessing services, self-sabotaging, long waiting lists.',
        'red_flag_criteria' => 'Flag if user says something like "nothing has worked for my child, I can’t carry on". Suggest seeking help / contacting Raft.',
    ],
    [
        'id' => 3,
        'type' => 'text',
        'category' => 'children',
        'section_id' => 'children',
        'section_title' => 'Children',
        'section_number' => 1,
        'total_sections' => 3,
        'label' => 'Raft Child Activities',
        'order' => 3,
        'question' => 'What activities could the Raft offer, that you feel would benefit your child or young person?',
        'participant_behavior' => 'Needs suggestions',
        'ai_guidance' => 'The Raft currently provides Lego-based therapeutic groups, cookery sessions and Christmas parties. Ideas: regular peer meet-ups, holiday clubs, independence skills / preparation for adulthood.',
        'red_flag_criteria' => 'Flag if someone states they attended a previous Raft event and did not feel safe or included. Encourage them to contact Raft.',
    ],
    [
        'id' => 4,
        'type' => 'text',
        'category' => 'children',
        'section_id' => 'children',
        'section_title' => 'Children',
        'section_number' => 1,
        'total_sections' => 3,
        'label' => 'Additional Child Needs',
        'order' => 4,
        'question' => 'Is there anything else you would like to tell us about your child’s needs or how The Raft could make a real difference to your family?',
        'transition_message' => 'Thank you for sharing your thoughts about your child’s needs. The next section focuses on your experiences as a parent or carer.',
        'participant_behavior' => 'Open ended',
        'ai_guidance' => 'Open ended question, no limits here.',
        'red_flag_criteria' => 'Flag any acute safeguarding or self-harm concerns.',
    ],

    // SECTION 2: Parents & Carers
    [
        'id' => 5,
        'type' => 'text',
        'category' => 'parents',
        'section_id' => 'parents',
        'section_title' => 'Parents & Carers',
        'section_number' => 2,
        'total_sections' => 3,
        'label' => 'Parent Main Challenges',
        'order' => 5,
        'question' => 'What are the main challenges you are facing right now, as a parent or carer, that are impacting your ability to care for your child?',
        'participant_behavior' => 'Struggling / Overwhelmed',
        'ai_guidance' => 'Ideas include: parenting, financial burdens, health issues, accessing support/services, feeling isolated, overwhelmed or in burnout, allegations / safeguarding concerns.',
        'red_flag_criteria' => 'Flag safeguarding concerns / risk of harm (automatic referral to safeguarding@theraftleicester.co.uk). Flag overwhelm/burnout/tired (suggest contacting social worker, trusted adult, FosterTalk, Adoption UK, or Raft).',
    ],
    [
        'id' => 6,
        'type' => 'text',
        'category' => 'parents',
        'section_id' => 'parents',
        'section_title' => 'Parents & Carers',
        'section_number' => 2,
        'total_sections' => 3,
        'label' => 'Parent Support Worked and Failed',
        'order' => 6,
        'question' => 'What support has helped you so far, and what has not worked?',
        'participant_behavior' => 'Struggling for suggestions',
        'ai_guidance' => 'Ideas include: day care / respite, self care activities, advocacy, support groups, training, books and resources.',
        'red_flag_criteria' => 'Flag if user says "nothing has worked, I can’t carry on". Suggest seeking help / contacting Raft.',
    ],
    [
        'id' => 7,
        'type' => 'text',
        'category' => 'parents',
        'section_id' => 'parents',
        'section_title' => 'Parents & Carers',
        'section_number' => 2,
        'total_sections' => 3,
        'label' => 'Raft Parent Activities',
        'order' => 7,
        'question' => 'What activities could the Raft offer, that you feel would benefit you as a parent or carer?',
        'participant_behavior' => 'Needs suggestions',
        'ai_guidance' => 'The Raft currently provides wellbeing sessions, a podcast, and signposting. Ideas: peer meet-ups, parenting groups, self care activities, practical needs/equipment, respite, befriending, toolkits, guidance sheets.',
        'red_flag_criteria' => 'Flag if user states they attended a previous Raft event and did not feel safe or included. Encourage contacting Raft.',
    ],
    [
        'id' => 8,
        'type' => 'text',
        'category' => 'parents',
        'section_id' => 'parents',
        'section_title' => 'Parents & Carers',
        'section_number' => 2,
        'total_sections' => 3,
        'label' => 'Raft Activity Barriers',
        'order' => 8,
        'question' => 'What are the barriers to you accessing Raft activities and how could they be overcome?',
        'transition_message' => 'Thank you for sharing your feedback as a parent or carer. The final section focuses on training and development opportunities.',
        'participant_behavior' => 'Accessibility or logistics issue',
        'ai_guidance' => 'Barriers: childcare, timing/location of events, language, accessibility, group size. Solutions: range of dates/times, include childcare, change format, range of locations.',
        'red_flag_criteria' => 'Flag if user makes a complaint about accessibility of Raft services. Ask them to email info@theraftleicester.co.uk.',
    ],

    // SECTION 3: Training & Development
    [
        'id' => 9,
        'type' => 'text',
        'category' => 'training',
        'section_id' => 'training',
        'section_title' => 'Training & Development',
        'section_number' => 3,
        'total_sections' => 3,
        'label' => 'Requested Training',
        'order' => 9,
        'question' => 'What training would you like the Raft to offer?',
        'participant_behavior' => 'Ideas requested',
        'ai_guidance' => 'Ideas: therapeutic parenting, trauma, attachment, neuroscience, additional needs, PACE, NVR (Non-Violence Resistance), bereavement, PTSD, mental health, first aid, EHCP application, supporting cultural identity, parent/carer reflective practice.',
        'red_flag_criteria' => 'Flag if user says they are overwhelmed and cannot continue as feel ill-equipped to do role effectively. Ask to seek help / contact social worker, trusted adult, or Raft (info@theraftleicester.co.uk).',
    ],
    [
        'id' => 10,
        'type' => 'text',
        'category' => 'training',
        'section_id' => 'training',
        'section_title' => 'Training & Development',
        'section_number' => 3,
        'total_sections' => 3,
        'label' => 'Preferred Training Format',
        'order' => 10,
        'question' => 'What format do you prefer for training (in-person, virtual, self-paced)?',
        'participant_behavior' => 'Format choice',
        'ai_guidance' => 'Allow people to state whatever format they prefer.',
        'red_flag_criteria' => 'None',
    ],
    [
        'id' => 11,
        'type' => 'text',
        'category' => 'training',
        'section_id' => 'training',
        'section_title' => 'Training & Development',
        'section_number' => 3,
        'total_sections' => 3,
        'label' => 'Training Timing Preference',
        'order' => 11,
        'question' => 'Do daytime (weekday or weekend) or evening training courses suit you better?',
        'participant_behavior' => 'Timing choice',
        'ai_guidance' => 'Give options to select more than one option if both daytime and evening are good.',
        'red_flag_criteria' => 'None',
    ],
    [
        'id' => 12,
        'type' => 'text',
        'category' => 'training',
        'section_id' => 'training',
        'section_title' => 'Training & Development',
        'section_number' => 3,
        'total_sections' => 3,
        'label' => 'Other Training Opportunities',
        'order' => 12,
        'question' => 'What other training and development opportunities do you need as a family or organisation?',
        'participant_behavior' => 'Ideas requested',
        'ai_guidance' => 'Ideas include: mentoring, written resources, signposting to helpful organisations, online communities.',
        'red_flag_criteria' => 'Flag if someone says they are struggling. Ask them to seek help, or get in touch with Raft.',
    ],
];
