<?php

return [
    // Category – Current Support & Overall Well-Being
    [
        'id' => 1,
        'type' => 'text',
        'category' => 'current_support',
        'label' => 'Helpful Support Types',
        'order' => 1,
        'question' => 'What types of support are currently most helpful to your family?',
        'participant_behavior' => 'Not Sure',
        'ai_guidance' => 'Mention social workers, therapists, support groups, schools, or family. Share anything helpful.',
    ],
    [
        'id' => 2,
        'type' => 'text',
        'category' => 'current_support',
        'label' => 'Most Supported',
        'order' => 2,
        'question' => 'Where do you feel most supported right now?',
        'participant_behavior' => 'Clarification: People? Home? Outside?',
        'ai_guidance' => 'Includes family, friends, schools, Raft, healthcare, or community groups.',
    ],
    [
        'id' => 3,
        'type' => 'text',
        'category' => 'current_support',
        'label' => 'Least Supported',
        'order' => 3,
        'question' => 'Where do you feel least supported right now?',
        'participant_behavior' => 'Takes long to answer',
        'ai_guidance' => 'Some people find this question difficult. Take your time or skip and come back later.',
        'takes_time' => true,
    ],
    [
        'id' => 4,
        'type' => 'text',
        'category' => 'current_support',
        'label' => 'Most Challenging Part',
        'order' => 4,
        'question' => 'What has been the most challenging part of fostering/adopting so far?',
        'transition_message' => 'Thank you for sharing your experiences so far. The next questions focus on emotional and mental health support.',
        'participant_behavior' => 'Takes long to answer',
        'ai_guidance' => 'Describe any significant challenge (e.g., trauma behaviors, navigating services, school).',
        'takes_time' => true,
    ],

    // Category – Emotional & Mental Health Support
    [
        'id' => 5,
        'type' => 'radio',
        'category' => 'emotional_support',
        'label' => 'Trauma-Informed Services',
        'order' => 5,
        'question' => 'Are trauma-informed services accessible in your area?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'What kind of services count?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 6,
        'type' => 'text',
        'category' => 'emotional_support',
        'label' => 'Mental Health Barriers',
        'order' => 6,
        'question' => 'What barriers have you (as the parent / carer) faced in accessing mental health support for your child?',
        'participant_behavior' => 'Clarification: Services or funding?',
        'ai_guidance' => 'Barriers: waiting lists, cost, lack of info, transport, or \'not knowing where to start\'.',
    ],
    [
        'id' => 7,
        'type' => 'radio',
        'category' => 'emotional_support',
        'label' => 'Parent Support Groups',
        'order' => 7,
        'question' => 'Would you benefit from parent-specific support groups?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'What would this involve?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 8,
        'type' => 'text',
        'category' => 'emotional_support',
        'label' => 'Caregiver Stress Management',
        'order' => 8,
        'question' => 'How do you manage caregiver stress or burnout?',
        'transition_message' => 'Thank you for sharing your thoughts about emotional and mental health support. The next questions focus on training and learning opportunities.',
        'participant_behavior' => 'Hesitation / Takes time',
        'ai_guidance' => 'Acknowledge demands of complex needs. Share as much/little as comfortable.',
        'takes_time' => true,
    ],

    // Category – Training & Education
    [
        'id' => 9,
        'type' => 'text',
        'category' => 'training',
        'label' => 'Helpful Training',
        'order' => 9,
        'question' => 'What additional training would be helpful to you right now?',
        'participant_behavior' => 'What options are there?',
        'ai_guidance' => 'Topics: trauma parenting, behavior management, attachment, emotional development.',
    ],
    [
        'id' => 10,
        'type' => 'radio',
        'category' => 'training',
        'label' => 'Trauma Behaviour Preparedness',
        'order' => 10,
        'question' => 'Do you feel adequately prepared to manage trauma-related behaviours?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'Not Sure / Definition of "adequately"',
        'ai_guidance' => 'Say: "This refers to having enough knowledge or support to manage trauma-related behaviours. If you\'re unsure, you can answer \'not sure\'."',
    ],
    [
        'id' => 11,
        'type' => 'radio',
        'category' => 'training',
        'label' => 'More Information on Topics',
        'order' => 11,
        'question' => 'Would you like more information on topics such as attachment, grief/loss, or behavioural regulation?',
        'options' => ['Yes', 'No'],
        'participant_behavior' => 'Information vs. Training?',
        'ai_guidance' => 'Focus is on guidance/info, but user can suggest training if preferred.',
    ],
    [
        'id' => 12,
        'type' => 'text',
        'category' => 'training',
        'label' => 'Training Accessibility',
        'order' => 12,
        'question' => 'How accessible are ongoing training opportunities?',
        'participant_behavior' => 'Clarification: Cost or location?',
        'ai_guidance' => 'Includes availability, location, cost, timing, or format.',
    ],
    [
        'id' => 13,
        'type' => 'text',
        'category' => 'training',
        'label' => 'Preferred Training Format',
        'order' => 13,
        'question' => 'What format do you prefer for training (in-person, virtual, self-paced)?',
        'transition_message' => 'Thank you for sharing your thoughts about training and learning opportunities. Your responses are very helpful in understanding what kinds of support might benefit families and carers.',
        'break_after' => true,
        'participant_behavior' => 'Definition of "self-paced"',
        'ai_guidance' => 'Self-paced = materials accessed at your own speed. Multiple formats allowed.',
    ],

    // Category – Respite & Practical Support
    [
        'id' => 14,
        'type' => 'radio',
        'category' => 'respite_support',
        'label' => 'Respite Care Access',
        'order' => 14,
        'question' => 'Do you have access to reliable respite care?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'What counts as respite?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 15,
        'type' => 'text',
        'category' => 'respite_support',
        'label' => 'Break Frequency',
        'order' => 15,
        'question' => 'How often do you feel you need a break but cannot get one?',
        'participant_behavior' => 'Measurement (days/weeks)?',
        'ai_guidance' => 'Answer in any way (days, weeks, or situations). Refers to time away from duties.',
    ],
    [
        'id' => 16,
        'type' => 'text',
        'category' => 'respite_support',
        'label' => 'Practical Stress Supports',
        'order' => 16,
        'question' => 'What practical supports would reduce stress (childcare, transportation, meal support, other)?',
        'participant_behavior' => '(No specific prompt)',
        'ai_guidance' => 'E.g., childcare, transportation, meal support.',
    ],
    [
        'id' => 17,
        'type' => 'text',
        'category' => 'respite_support',
        'label' => 'Financial Strains',
        'order' => 17,
        'question' => 'Are there financial strains related to fostering/adoption? Please expand.',
        'participant_behavior' => 'Do I have to explain?',
        'ai_guidance' => 'If comfortable, briefly describe the pressures your family experiences.',
    ],
    [
        'id' => 18,
        'type' => 'text',
        'category' => 'respite_support',
        'label' => 'Financial Resources',
        'order' => 18,
        'question' => 'What additional financial resources would be helpful?',
        'transition_message' => 'Thank you for sharing your thoughts about practical support and resources. The next questions focus on your child\'s experience in school and educational support.',
        'participant_behavior' => 'What options are there?',
        'ai_guidance' => 'E.g., funding, subsidies, assistance with therapy or education costs.',
    ],

    // Category – School & Educational Advocacy
    [
        'id' => 19,
        'type' => 'radio',
        'category' => 'school_advocacy',
        'label' => 'School Understanding',
        'order' => 19,
        'question' => 'Do you feel your child\'s school understands their needs?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'Not sure',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 20,
        'type' => 'radio',
        'category' => 'school_advocacy',
        'label' => 'Advocacy Challenges',
        'order' => 20,
        'question' => 'Have you experienced challenges advocating for your child at school?',
        'options' => ['Yes', 'No'],
        'participant_behavior' => 'Definition of "advocating"',
        'ai_guidance' => 'Say: "Advocating means speaking with schools to ensure support for your child." Then ask: "Would you like to share an example?"',
    ],
    [
        'id' => 21,
        'type' => 'radio',
        'category' => 'school_advocacy',
        'label' => 'SEN / EHCP Support',
        'order' => 21,
        'question' => 'Do you need help navigating SEN support and / or EHCPs?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'What is SEN/EHCP?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 22,
        'type' => 'text',
        'category' => 'school_advocacy',
        'label' => 'Educational Supports',
        'order' => 22,
        'question' => 'What educational supports would benefit your child?',
        'transition_message' => 'Thank you for sharing your experiences with school and educational support.',
        'break_after' => true,
        'participant_behavior' => 'What kinds exist?',
        'ai_guidance' => '**RAFT input needed**',
    ],

    // Category – Medical & Specialised Services
    [
        'id' => 23,
        'type' => 'radio',
        'category' => 'medical_services',
        'label' => 'Medical Provider Knowledge',
        'order' => 23,
        'question' => 'Are medical providers knowledgeable about adoption/foster-related trauma?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'Which doctors?',
        'ai_guidance' => 'Includes GPs, paediatricians, therapists, or healthcare professionals.',
    ],
    [
        'id' => 24,
        'type' => 'radio',
        'category' => 'medical_services',
        'label' => 'Specialised Services Assistance',
        'order' => 24,
        'question' => 'Do you need assistance finding specialised services (such as OT, speech / behavioural therapy, additional needs diagnoses)?',
        'options' => ['Yes', 'No'],
        'transition_message' => 'Thank you for sharing your thoughts about healthcare and specialised services. The next questions focus on social and community support.',
        'participant_behavior' => '(No specific prompt)',
        'ai_guidance' => 'E.g., OT, speech/behavioural therapy, diagnoses.',
    ],

    // Category – Social & Community Support
    [
        'id' => 25,
        'type' => 'radio',
        'category' => 'social_support',
        'label' => 'Connection to Foster/Adoptive Families',
        'order' => 25,
        'question' => 'Do you feel connected to other foster/adoptive families?',
        'options' => ['Yes', 'No'],
        'participant_behavior' => '(No specific prompt)',
        'ai_guidance' => 'Say: "Would you find it helpful if Raft supported connection opportunities?"',
    ],
    [
        'id' => 26,
        'type' => 'radio',
        'category' => 'social_support',
        'label' => 'Peer Support Groups',
        'order' => 26,
        'question' => 'Would you participate in peer support groups if available?',
        'options' => ['Yes', 'No', 'Not sure'],
        'participant_behavior' => 'What is a peer group?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 27,
        'type' => 'radio',
        'category' => 'social_support',
        'label' => 'Extended Family Understanding',
        'order' => 27,
        'question' => 'Do extended family and friends understand your child\'s needs?',
        'options' => ['Yes', 'No', 'Not sure'],
        'transition_message' => 'Thank you for sharing your thoughts about social and community support. The final questions focus on future planning and the kinds of support that could help families thrive over time.',
        'participant_behavior' => '(No specific prompt)',
        'ai_guidance' => 'Say: "This question can be answered with a simple Yes or No."',
    ],

    // Category – Long-Term & Future Planning
    [
        'id' => 28,
        'type' => 'text',
        'category' => 'future_planning',
        'label' => 'Child Future Concerns',
        'order' => 28,
        'question' => 'What concerns do you have about your child\'s future (such as adolescence, adulthood, transitions)?',
        'participant_behavior' => 'Not Sure',
        'ai_guidance' => 'Share anything important regarding adolescence, adulthood, or transitions.',
    ],
    [
        'id' => 29,
        'type' => 'text',
        'category' => 'future_planning',
        'label' => 'Long-Term Support',
        'order' => 29,
        'question' => 'What additional supports would help your family thrive long-term?',
        'participant_behavior' => 'What kind of supports?',
        'ai_guidance' => 'Say: "I don\'t have knowledge about this, I will notify Raft about this."',
    ],
    [
        'id' => 30,
        'type' => 'text',
        'category' => 'future_planning',
        'label' => 'New Support Service Design',
        'order' => 30,
        'question' => 'If you could design one new support service, what would it be?',
        'participant_behavior' => 'Not Sure',
        'ai_guidance' => 'Idea can be simple or ambitious.',
    ],
];
