<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class SafeguardingAlertMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    /**
     * Create a new message instance.
     */
    public function __construct(
        public string $sessionId,
        public int $questionId,
        public string $questionText,
        public string $userResponse,
        public string $flagType,
        public string $flagSeverity,
        public string $flagReason,
        public string $recipientEmail = 'safeguarding@theraftleicester.co.uk',
        public ?string $organizationName = null,
    ) {}

    /**
     * Get the message envelope.
     */
    public function envelope(): Envelope
    {
        $prefix = strtoupper($this->flagSeverity);
        $organization = strtoupper($this->organizationName ?? 'SCOPE AI');

        return new Envelope(
            to: [$this->recipientEmail],
            subject: "[{$organization} ALERT - {$prefix}] Survey Response Flagged ({$this->flagType}) - Session {$this->sessionId}"
        );
    }

    /**
     * Get the message content definition.
     */
    public function content(): Content
    {
        $organization = e($this->organizationName ?? 'SCOPE AI');

        return new Content(
            htmlString: "
                <h2>{$organization} - Survey Response Alert</h2>
                <p><strong>Session ID:</strong> ".e($this->sessionId)."</p>
                <p><strong>Severity:</strong> <span style='color: red; font-weight: bold;'>".e(strtoupper($this->flagSeverity)).'</span></p>
                <p><strong>Flag Type:</strong> '.e($this->flagType).'</p>
                <p><strong>Reason:</strong> '.e($this->flagReason).'</p>
                <hr>
                <p><strong>Question (#'.e($this->questionId).'):</strong> '.e($this->questionText)."</p>
                <blockquote style='background: #f8f9fa; border-left: 4px solid #dc3545; padding: 10px; font-size: 1.1em;'>
                    ".nl2br(e($this->userResponse)).'
                </blockquote>
                <hr>
                <p><small>This notification was automatically generated by SCOPE AI Flag Detection System.</small></p>
            '
        );
    }
}
